properties:
  application.root: /user/osboxes/apps/aurora_dataload
  datasources.data.root: ${application.root}/datasets
  datasources.metadata.root: ${application.root}/metadata
  impala.db.name: pc_aurora_uat_analysis
  impala.jdbc.driverClass: com.cloudera.impala.jdbc.Driver
  impala.jdbc.url: jdbc:impala://quickstart-bigdata:21050;AuthMech=0;
  spark.partitionColumn.daily: dt_business_date
  spark.log.table.name: ${impala.db.name}.t_dataload_log
  spark.log.table.partitionColumn: month
  yarn.ui.url: http://quickstart-bigdata:8088/cluster/app

dataSources:
  -
    id: OCS_DAILY
    metadataFilePath: ${datasources.metadata.root}/ocs_daily.json

